const Tag = {
	NUMBER: 'NUMBER',
	STRING: 'STRING',
	WORD: 'WORD',

	// SYMBOLS
	L_BRACE: 'L_BRACE',
	R_BRACE: 'R_BRACE',
	L_PARENTHESIS: 'L_PARENTHESIS',
	R_PARENTHESIS: 'R_PARENTHESIS',
	PLUS: 'PLUS',
	MINUS: 'MINUS',
	MULTIPLY: 'MULTIPLY',
	MORE: 'MORE',
	LESS: 'LESS',
	EQUAL: 'EQUAL',
	MORE_EQUAL: 'MORE_EQUAL',
	LESS_EQUAL: 'LESS_EQUAL',
	LOOSE_EQUAL: 'LOOSE_EQUAL',
	STRICT_EQUAL: 'STRICT_EQUAL',
	SEMICOLON: 'SEMICOLON',


	// KEYWORDS
	IF: 'IF',
	ELSE: 'ELSE',
	DO: 'DO',
	WHILE: 'WHILE',
	VAR: 'VAR',


	// SPECIAL
	EOF: 'EOF',
	ID: 'ID',
	E: 'E',
	S: 'S'
};

export default Tag;