declare const Tag: {
    NUMBER: string;
    WORD: string;
    L_BRACE: string;
    R_BRACE: string;
    L_PARENTHESIS: string;
    R_PARENTHESIS: string;
    PLUS: string;
    MINUS: string;
    MULTIPLY: string;
    MORE: string;
    LESS: string;
    EQUAL: string;
    MORE_EQUAL: string;
    LESS_EQUAL: string;
    LOOSE_EQUAL: string;
    STRICT_EQUAL: string;
    IF: string;
    ELSE: string;
    DO: string;
    WHILE: string;
    EOF: string;
    ID: string;
    E: string;
    S: string;
};
export default Tag;
